formulation changes sheet 1 and 2
FIUS/jvk pull request #156
Opened 2023-09-30 18:45 UTC by Sara424242

2023-09-30 23:46 UTC, graefjk requested changes

2023-09-30 23:46 UTC, graefjk commented on sheets/2/exercise-5.tex
> +    \item Zeichne mit den aufgehobenen Münzen eine Linie auf der mittleren Spur, beginnend auf  neben Neo.
```suggestion
    \item Zeichne mit den aufgehobenen Münzen eine Linie auf der mittleren Spur, beginnend auf dem Feld neben Neo.
```

2023-09-30 23:46 UTC, graefjk commented on sheets/2/exercise-2.tex
> +        Überlege dir wie du an Tank's Stelle ein solches Hindernis an einer geeigneten Stelle platzieren kann und platziere es dort. Falls du nicht weißt wie man ein Hinderniss palziert, schaue dir n
```suggestion
        Überlege dir wie du an Tank's Stelle ein solches Hindernis an einer geeigneten Stelle platzieren kann und platziere es dort. Falls du nicht weißt wie man ein Hindernis plaziert, schaue dir nochmal Blatt 1 Aufgabe 3 oder die Klasse \lstinline{Sheet2Task2} genauer an.
```

2023-09-30 23:46 UTC, graefjk commented on sheets/2/exercise-4.tex
> +    Das beispilehafte IF-Statement bedeuted informal, dass falls player.canMove() den boolschen Wert \lstinline{true} hat, wird player.move() ausgeführt. Falls player.canMove() den boolschen Wert \ls
```suggestion
    Das beispielhafte IF-Statement bedeutet informal, dass falls player.canMove() den bool'schen Wert \lstinline{true} hat, wird player.move() ausgeführt. Falls player.canMove() den bool'schen Wert \lstinline{false} hat wird der Code in den geschweiften Klammern übersprungen.
```

2023-09-30 23:46 UTC, graefjk commented on sheets/2/exercise-4.tex
> +    Für sowohl das IF- als auch das ELSE-Statement gilt, dass in den geschweiften Klammern belibig viel Code stehen kann, nicht nur eine Zeile wie in unserem Beispiel.
```suggestion
    Für sowohl das IF- als auch das ELSE-Statement gilt, dass in den geschweiften Klammern beliebig viel Code stehen kann, nicht nur eine Zeile wie in unserem Beispiel.
```

2023-10-01 09:45 UTC, becknik commented
Sehr schade zu sehen, dass viele von meinen Vorschlägen im Review von @Sara424242 abgelehnt wurden... Ich denke ich mache einfach selber mal einen PR auf, denn die Blätter haben meiner Meinung nach noch viel Bedarf an Erklärungen...

2023-10-01 12:05 UTC, becknik reviewed
Thanks for accepting some of my changes.
Added some commits to enhance the formatting from the MD text copied to the Latex sources and made some further minor changes.

2023-10-01 14:54 UTC, graefjk commented on sheets/2/exercise-2.tex
> +Für alle die Matrix nicht kennen, Tank ist der Antagonist.
Stimmt nicht, Tank ist der typ der Neo hilft wieder in die Matrix zu kommen.

2023-10-01 15:01 UTC, graefjk requested changes

2023-10-01 15:01 UTC, graefjk commented on sheets/2/exercise-4.tex
> +    Die Funktion \lstinline{player.canMove()} zum Beispiel gibt den boolschen Wert \lstinline{true} zurück wenn der Player (z.B. Neo) eine Schritt in seine Blickrichtung gehen kann, also auf diesem F
```suggestion
    Die Funktion \lstinline{player.canMove()} zum Beispiel gibt den bool'schen Wert \lstinline{true} zurück wenn der Player (z.B. Neo) eine Schritt in seine Blickrichtung gehen kann, also auf diesem Feld sind keine Hindernisse.
```

2023-10-01 15:01 UTC, graefjk commented on sheets/2/exercise-5.tex
> +        \textbf{Hinweis}: Hier kannst du entweder die Abfloge direkt kodieren oder mit Variablen vom Typ \lstinline{boolean} und if-Verzweigungen aus Aufgabe 4 arbeiten.
```suggestion
        \textbf{Hinweis}: Hier kannst du entweder die Abfolge direkt kodieren oder mit Variablen vom Typ \lstinline{boolean} und if-Verzweigungen aus Aufgabe 4 arbeiten.
```

2023-10-01 15:08 UTC, graefjk approved these changes

2023-10-01 15:11 UTC, merged